### ISSUE TITLE
Out of the box lib fuzzer error

### ISSUE THREAD

**Issue by jayzalowitz** [mobilecoinofficial/full-service#117]
For the script at https://gist.github.com/jayzalowitz/fd7c8b76c3dce401f33a7fb2527b118b (see userdata section for ubuntu script)
 
Im getting

 cargo build --release -p mc-full-service
    Updating git repository `https://github.com/xoloki/AEADs`
    Updating git repository `https://github.com/eranrund/bulletproofs`
    Updating git repository `https://github.com/jcape/grpc-rs`
    Updating git submodule `https://github.com/pingcap/grpc.git`
    Updating git submodule `https://github.com/abseil/abseil-cpp.git`
    Updating git submodule `https://github.com/google/benchmark`
    Updating git submodule `https://github.com/google/bloaty.git`
    Updating git submodule `https://github.com/google/googletest.git`
    Updating git submodule `https://chromium.googlesource.com/chromium/llvm-project/llvm/lib/Fuzzer`
error: failed to resolve patches for `https://github.com/rust-lang/crates.io-index`

Caused by:
  failed to load source for dependency `grpcio`

Caused by:
  Unable to update https://github.com/jcape/grpc-rs?rev=2ad042e9e65ecb664a60e034d0a899a8760d81d3#2ad042e9

Caused by:
  failed to update submodule `grpc-sys/grpc`

Caused by:
  failed to update submodule `third_party/bloaty`

Caused by:
  failed to update submodule `third_party/libFuzzer`

Caused by:
  failed to fetch submodule `third_party/libFuzzer` from https://chromium.googlesource.com/chromium/llvm-project/llvm/lib/Fuzzer

Caused by:
  error reading from the zlib stream; class=Zlib (5)
  
 Something obvious im not doing?

**Comment by BrianCorbin** [comment]
Closing for now. If issue still persists, please comment and reopen.
