### ISSUE TITLE
Missing downloads for v1.0.0-pre.6

### ISSUE THREAD

**Issue by suddenlyfleck** [mobilecoinofficial/full-service#168]
Hi,

The downloadable binaries linked in [https://github.com/mobilecoinofficial/full-service/releases/tag/v1.0.0-pre.6](https://github.com/mobilecoinofficial/full-service/releases/tag/v1.0.0-pre.6) are missing.

Since they are mentionde in the description, this seems not to be intended.

**Comment by BrianCorbin** [comment]
The follow up releases should have proper binaries with them. If you need v1.0.0-pre.6 specifically let me know and I'll make it happen :)
