### ISSUE TITLE
Store and return raw data, not protobuf data, in database and API responses

### ISSUE THREAD

**Issue by eranrund** [mobilecoinofficial/full-service#201]
full-service stores protobuf-encoded data in a few places: https://github.com/mobilecoinofficial/full-service/blob/main/full-service/src/db/txo.rs#L359-L361
It should've stored the actual data, there is no reason to protobuf encode it, but here we are.

This becomes a problem in API responses such as https://github.com/mobilecoinofficial/full-service/blob/main/full-service/src/json_rpc/txo.rs#L144-L146

The expectation is that these fields will contain the actual data - for example `public_key` should be 32 bytes (so 64 hex-encoded string), but instead it is longer as instead of being the actual key data it is the protobuf-encoded version.

This results in a few annoyances:
1) If someone copy-pastes this key and try to query the ledger for it, or search for it in the block explorer, they will come empty handed and might think the key is not actually in the ledger instead of realizing it is just in a different format
2) Converting between "full-service receipts" and protobuf receipts is more confusing, since sometimes you have the raw data and sometimes the protobuf wrapped version. For example compare https://github.com/mobilecoinofficial/full-service/blob/main/python-utils/mc_util/__init__.py#L112-L114 and https://github.com/mobilecoinofficial/full-service/blob/main/python-utils/mc_util/__init__.py#L119-L121

In every other part of the system we represent a TxOut public_key (and other keys) as just the raw 32 bytes, so this should be the case in full-service responses as well.

**Comment by BrianCorbin** [comment]
Are you suggesting that we should just hex::encode the data and not use mc_util_serial::encode? If so, I do agree with that and think it's important to not store hex encoded protobuf, but the actual hex encoded data.

**Comment by Shramp** [comment]
summary: remove mc_util_serial encoding and decoding from (almost?) everywhere in full-service

**Comment by Shramp** [comment]
Something to figure out if we change this: how to make the changes backwards compatible. If we're no longer storing the protobuff encoded data, FS needs to know whether existing data is protobuff or not. Maybe an is_protobuff check that tries to decode and if it fails, return the raw data?

**Comment by BrianCorbin** [comment]
Let's postpone this until further discussion can be had in a larger group setting

**Comment by Shramp** [comment]
Convert keys and hints, but not other things (like full txo objects)

**Comment by Shramp** [comment]
Hey @eranrund we are going to put this on hold. Any changes to what current FS endpoints return would be breaking changes for current users and we are not gonna do that right now.

**Comment by eranrund** [comment]
Does `full-service` have a plan for API versioning? 
Alternatively, maybe it is possible to workaround this by adding another field with a `_bytes` prefix, e.g. `view_private_key` and `view_private_key_bytes` - where the new field is just the raw bytes. When used as input, both should be optional but one of them must be specified and when used as output both are provided. I am not sure how confusing this would end up being, but maybe it is easier to explain that than explaining the need to go through a protobuf.

**Comment by BrianCorbin** [comment]
To update, this will be addressed in the v2.0 of Full Service
