### ISSUE TITLE
Transactions sent via full service which resolve as "tx_status_failed" are successfully received by a receiving signal account

### ISSUE THREAD

**Issue by iamalwaysuncomfortable** [mobilecoinofficial/full-service#230]
Sometimes when transactions are built/submitted via full service and receipts are sent to the receiving signal wallet (via the process below) full service states the transaction has failed, but the receiver of the receipt shows that transaction succeeds & that their balance has increased. This is unexpected and makes it hard for users of full service to do business logic which depends on successful transaction deliveries.

Steps To Repeat
1. Create tx_proposal 
`
{"method": "build_transaction", "params": {"account_id":"SENDER_ACCT", "recipient_public_address":"SIGNAL_USER_RECEIVING", "amount_pmob":"1400000000", "comment":"prepay"}}
`

2. Submit tx_proposal
`
{"method":"submit_transaction","params":{"tx_proposal":proposal, "comment":"prepay", "account_id":"SENDER_ACCT"}}
`

3. Create Receiver Receipts and send to signal recipient for confirmation
`
{"method": "create_receiver_receipts", params: {"tx_proposal":proposal, "account_id":"SENDER_ACCT"}}
`

4. Check transaction log_id until success or failure reported - Failure is reported:
`
{"method": "get_transaction_log", "params": {"transaction_log_id":"REDACTED"}}
`
Result:
`
[{'object': 'transaction_log', 'transaction_log_id': 'REDACTED', 'direction': 'tx_direction_sent', 'is_sent_recovered': None, 'account_id': 'SENDER_ACCT', 'input_txos': [{'txo_id_hex': 'REDACTED', 'recipient_address_id': '', 'value_pmob': '4000000000'}, {'txo_id_hex': 'REDACTED', 'recipient_address_id': '', 'value_pmob': '1000000000'}], 'output_txos': [{'txo_id_hex': 'REDACTED', 'recipient_address_id': 'SIGNAL_USER_RECEIVING', 'value_pmob': '1400000000'}], 'change_txos': [{'txo_id_hex': 'REDACTED', 'recipient_address_id': '', 'value_pmob': '3200000000'}], 'assigned_address_id': None, 'value_pmob': '1400000000', 'fee_pmob': '400000000', 'submitted_block_index': '160564', 'finalized_block_index': None, 'status': 'tx_status_failed', 'sent_time': '2022-01-16 19:36:30 UTC', 'comment': 'prepay', 'failure_code': None, 'failure_message': None}]
`

5. Despite failure being reported the receiving account reports the transaction as succeeded and gets a resulting increase in balance.
![image](https://user-images.githubusercontent.com/26438809/149684912-e9cdc67d-4498-448b-9419-09f2a1255c00.png)

**Comment by BrianCorbin** [comment]
Hmm, we'll look in to this right away. Is this a consistent issue every time, or does it happen at random?

**Comment by BrianCorbin** [comment]
Could you confirm that this is still happening with the new release?

**Comment by BrianCorbin** [comment]
This should have been resolved in the latest release. If issue persists, please comment and reopen :)
