### ISSUE TITLE
Upgrade of full service binaries fails if gift codes exist in wallet.db

### ISSUE THREAD

**Issue by iamalwaysuncomfortable** [mobilecoinofficial/full-service#243]
Steps to reproduce
1. Have persistent directory with the following files: ledger-db  lost+found  wallet.db  wallet.db-shm  wallet.db-wal with gift codes in it
2. Upgrade to latest [full service binaries ](https://github.com/mobilecoinofficial/full-service/releases/download/v1.3.0/linux-v1.3.0.tar.gz) from v1.1.0
3. Launch upgraded full service with [this invocation](https://public.getpost.workers.dev/?key=01FTWDTFWB5CGBG0W8RB0XFK62&raw) 

The following error occurs immediately after launch:

`2022-02-02T04:12:40.466` [info]OH NO, WE CRASHED :( thread main on ./full-service
2022-02-02T04:12:40.466 [info]Details: panicked at 'Database contains invalid foreign keys: [("gift_codes", 21, "txos", 0), ("gift_codes", 22, "txos", 0), ("gift_codes", 57, "txos", 0)]', full-service/src/db/wallet_db.rs:136:13)`

**Comment by BrianCorbin** [comment]
awesome, I'll take a look at that asap!

**Comment by BrianCorbin** [comment]
This is getting resolved in the next release! Thank you :)
