### ISSUE TITLE
Update InsufficientFundsUnderMaxSpendable Error to indicate the actual max spendable amount

### ISSUE THREAD

**Issue by BrianCorbin** [mobilecoinofficial/full-service#294]
Currently, this error appears something like so

```
"code": -32603,
        "message": "InternalError",
        "data": {
            "server_error": "TransactionBuilder(WalletDb(InsufficientFundsUnderMaxSpendable(\"Max spendable value in wallet: 147912556221819, but target value: 147912956221819\")))",
```
but the max spendable value is not including the transaction fee, which it should.

The transaction fee can be attained by querying consensus, and if not available then using the default MOB transaction fee found in the mobilecoin library.

**Comment by Shramp** [comment]
going to combine this with https://github.com/mobilecoinofficial/full-service/issues/295

**Comment by Shramp** [comment]
PR: https://github.com/mobilecoinofficial/full-service/pull/314
