### ISSUE TITLE
Deleting an account then re-importing it causes a unique key error in the database.

### ISSUE THREAD

**Issue by christian-oudard** [mobilecoinofficial/full-service#31]
1. Create an account.
2. Delete the account.
3. Re-import it.

```{"error": "Database(Diesel(DatabaseError(UniqueViolation, "UNIQUE constraint failed: assigned_subaddresses.assigned_subaddress_b58")))"}```

Also, this error response is illegal JSON, because it has unescaped quotes in the error value.

**Comment by sugargoat** [comment]
Thank you for reporting! Will look into this - the error handling is being improved to be proper json - currently in review in #19
