### ISSUE TITLE
Add Endpoints for querying balances per address

### ISSUE THREAD

**Issue by BrianCorbin** [mobilecoinofficial/full-service#322]

**Comment by Shramp** [comment]
this already exists, just need to document https://github.com/mobilecoinofficial/full-service/blob/develop/full-service/src/service/balance.rs#L204

**Comment by Shramp** [comment]
this is actually already documented. moving this to done
https://mobilecoin.gitbook.io/full-service-api/accounts/balance/get_balance_for_address
