### ISSUE TITLE
Full Service fails to start on Ubuntu 22.04

### ISSUE THREAD

**Issue by kareldonk** [mobilecoinofficial/full-service#500]
**Describe the bug**
The full service is built with OpenSSL 1.1 as a dependency and does not work on Ubuntu 22.04 which ships with OpenSSL 3.0. This affects the Desktop Wallet which fails to start the full service on Ubuntu 22.04. (It does work on Ubuntu 20.04 which has OpenSSL 1.1).

**To Reproduce**
Try running the desktop wallet on Ubuntu 22.04. Won't start because libssl and libcrypto 1.1 are not found. To verify run the command `ldd full-service` in the Desktop Wallet installation folder `/opt/MobileCoin Wallet/full-service-bin` which produces output similar to this:

```
opt/MobileCoin Wallet/full-service-bin$ ldd full-service
	linux-vdso.so.1 (0x00007ffc5e346000)
	libssl.so.1.1 => Not found
	libcrypto.so.1.1 => Not found
	libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f2d067ab000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f2d0678b000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f2d06786000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f2d0669d000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f2d06698000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f2d06470000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f2d08496000)
```

**Expected behavior**
Expect the Desktop Wallet to be able to start the full service on Ubuntu 22.04. Perhaps ship all dependency modules with the full service?

**Environment (please complete the following information):**
 - OS:  Ubuntu
 - Version 22.04

**Workaround**
Manually install libssl and libcrypto 1.1 on Ubuntu 22.04.

**Comment by briancorbin** [comment]
Working on an update that should be out sometime today. There was an openSSL dependency in Full Service that has been removed as of 1.9.3, but the latest Desktop Wallet is using 1.9.2.

**Comment by briancorbin** [comment]
https://github.com/mobilecoinofficial/desktop-wallet/releases/tag/v1.6.4

This release should resolve the issue! Let me know if you're still experiencing any issues :)
