### ISSUE TITLE
`get_block` by `txo_pubkey`

### ISSUE THREAD

**Issue by sugargoat** [mobilecoinofficial/full-service#505]
**Is your feature request related to a problem? Please describe.**
We would like to provide searchability for blocks by txo_pubkey, as this is typcially exercised when resolving disputes. (A sender or recipient has a txo_pubkey, and they want to determine whether it landed in the blockchain or not). This would also be a killer feature for the block explorer.

Similarly, we could provide searching by `key_image` or other aspects of the TXO.

**Describe the solution you'd like**
Add `txo_pubkey` as an optional param for `get_block`, and make `block_index` optional

**Comment by briancorbin** [comment]
Resolved by https://github.com/mobilecoinofficial/full-service/pull/615
