### ISSUE TITLE
Comments do not work in a two-step build and submit transaction flow

### ISSUE THREAD

**Issue by eranrund** [mobilecoinofficial/full-service#593]
**Describe the bug**

When creating a transaction using `build_transaction` and later submitting it using `submit_transaction`, one can specify a [comment](https://github.com/mobilecoinofficial/full-service/blob/develop/full-service/src/json_rpc/v1/api/request.rs#L216)

However, this comment gets discarded. It seems like the reason for this is that [`build_transaction`](https://github.com/mobilecoinofficial/full-service/blob/develop/full-service/src/json_rpc/v1/api/wallet.rs#L274) calls [this](https://github.com/mobilecoinofficial/full-service/blob/511f13f48f178d8a1ee2aaf87494e3fdaaa2f9ab/full-service/src/service/transaction.rs#L449) and this results in a new `TransactionLog` being inserted into the database.
[`submit_transaction`](https://github.com/mobilecoinofficial/full-service/blob/develop/full-service/src/json_rpc/v1/api/wallet.rs#L1048) will then call [this](https://github.com/mobilecoinofficial/full-service/blob/develop/full-service/src/json_rpc/v1/api/wallet.rs#L1048) which will call [this](https://github.com/mobilecoinofficial/full-service/blob/dbd6de7eac7a0bcae2d52314a23fc37da9814462/full-service/src/db/transaction_log.rs#L386) - which doesn't update the comment.

I have not tested whether `build_and_submit_transaction` behaves properly and stores the comment.

**To Reproduce**
Build a transaction using `build_transaction` and then submit using `submit_transaction` while providing a comment.

**Expected behavior**
The comment should make it into the transaction log database.

**Comment by briancorbin** [comment]
This has been resolved with #656
