### ISSUE TITLE
Claim URL bug

### ISSUE THREAD

**Issue by jruffer** [mobilecoinofficial/full-service#665]
**Describe the bug**
Claim your URL under the QRcode does not properly update.

**To Reproduce**
SIgnup as a new users on android and complete the new wallet process. Land on home page. Click QRcode and click claim URL. Put in the desired custom name. 
Then you will see the new/correct url in the UI but the copy link will show some type of ID instead of proper url.  If you go to the new URL it will be in coming soon mode and the url with the tag will user not found. 

**To Fix**
If you go into profile add bio or update then publish your claimed URL will work. 

**Expected behavior**
Either do not show claim your URL or shadow it until the profile is properly published or have a ? with a hover state that explains you need to publish profile before claim your URL will properly work.

**Environment (please complete the following information):**
 - OS: [android13]
 - Device: pixel 7pro, pixel 3xl, pixel7

**<details><summary>Images</summary>**

```
Images below

https://cdn.discordapp.com/attachments/852641988024729631/1064642066426118225/IMG_20230116_152648.png
https://cdn.discordapp.com/attachments/852641988024729631/1064642066677772360/IMG_20230116_152700.png
https://cdn.discordapp.com/attachments/852641988024729631/1064642066921029672/IMG_20230116_152657.png
https://cdn.discordapp.com/attachments/852641988024729631/1064642067122372749/IMG_20230116_152653.png
https://cdn.discordapp.com/attachments/852641988024729631/1064642723002450000/IMG_20230116_152951.png
https://cdn.discordapp.com/attachments/852641988024729631/1064642723266703441/IMG_20230116_152948.png


```

</details>

**Additional context**

**Comment by briancorbin** [comment]
To report issues with Moby, please do that through the app! Full Service is a different project
