### ISSUE TITLE
Compilation Failure

### ISSUE THREAD

**Issue by crassd** [mobilecoinofficial/full-service#95]
Method to reproduce: git pull latest
Compile with: SGX_MODE=HW IAS_MODE=PROD CONSENSUS_ENCLAVE_CSS=/coin/service/consensus-enclave.css cargo build --release -p mc-full-service

`   Compiling mc-full-service v0.1.0 (/coin/service/full-service)
error[E0308]: mismatched types
   --> full-service/src/config.rs:186:20
    |
186 |                 Ok(FogResolver::new(report_responses, verifier))
    |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected struct `mc_fog_report_validation::FogResolver`, found enum `std::result::Result`
    |
    = note: expected struct `mc_fog_report_validation::FogResolver`
                 found enum `std::result::Result<mc_fog_report_validation::FogResolver, mc_util_uri::uri::UriParseError>`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0308`.
error: could not compile `mc-full-service`.

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: build failed
`

**Comment by sugargoat** [comment]
Thank you for reporting - can you try the latest on the `develop` branch? 

We'll look into how `main` got into this state, meanwhile, and then we'll cut a release to bring `main` up to `develop`.

**Comment by crassd** [comment]
@sugargoat branch: develop compiled without issue. Thank you.
